BASE_TASK_CONFIG_PATH: "configs/tasks/pointnav.yaml"
TRAINER_NAME: "bc"
ENV_NAME: "NavRLEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
VIDEO_OPTION: ["disk", "tensorboard"]
TENSORBOARD_DIR: "tb"
VIDEO_DIR: "video_dir"
TEST_EPISODE_COUNT: 2
EVAL_CKPT_PATH_DIR: "data/bc_checkpoints"
NUM_PROCESSES: 1
SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR"]
CHECKPOINT_FOLDER: "data/bc_checkpoints"
NUM_UPDATES: 10000
LOG_INTERVAL: 10
CHECKPOINT_INTERVAL: 50

IMITATION:
    EXPERT:
        mode: "greedy"
        num_episodes: 10
        split_dataset: 0.5
        record_images: False
        iteration_split: 5
        dataset_path: "data/datasets/imitlearn/{split}/"
        log_file: train.log
    BC:
        weight_decay: 0.0
        eps: 1e-8
        num_epochs: 4
        batch_size: 16
        learning_rate: 0.001
        num_workers: 0
        hidden_size: 512
        pin_memory: True
        checkpoint_interval: 8





